@HotelListing.Api_HostAddress = http://localhost:5107


// HOTELS 
//
//
//
//
//
//
// ENDPOINTS
GET {{HotelListing.Api_HostAddress}}/api/hotels

###
@idHotel=6
GET {{HotelListing.Api_HostAddress}}/api/hotels/{{idHotel}}

###

POST {{HotelListing.Api_HostAddress}}/api/hotels
Content-Type: application/json

{
  "Name": "Test Hotel",
  "Address": "123 Main St",
  "Rating": 4.5,
  "CountryId": 1
}

###

PUT {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  //Hotel
}

###

DELETE {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###





// COUNTRIES 
//
//
//
//
//
//
// ENDPOINTS

GET {{HotelListing.Api_HostAddress}}/api/countries

###

@id=1
GET {{HotelListing.Api_HostAddress}}/api/countries/{{id}}

###

POST {{HotelListing.Api_HostAddress}}/api/countries
Content-Type: application/json

{
"Name":"Test country",
"ShortName":"TC"
}

###

PUT {{HotelListing.Api_HostAddress}}/api/countries/{{id}}
Content-Type: application/json

{
  "countryId": 2,
  "name": "Jamaica",
  "shortName": "JM"
}

###

DELETE {{HotelListing.Api_HostAddress}}/api/countries/{{id}}

###

